const catchError = require('./catchError');

module.exports = {
  catchError,
};